<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <OutputType>WinExe</OutputType>
    <Platforms>x64;x86</Platforms>
    <RootNamespace>ViewVb</RootNamespace>
    <TargetFrameworks>
      net48;
    </TargetFrameworks>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <Import Project="..\Props\OutputApps.props" />

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="10.0.*" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <ProjectReference Include="..\Cli.NetFramework4.8\Wrapper.Net48.vcxproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\WpfControl\WpfControl.NetOld.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Models\MySampleModel.vb" />
    <Compile Include="ViewModels\SampleViewModel.vb" />
    <Compile Include="Views\MainWindow.xaml.vb" />
    <Compile Include="WinAPI.vb" />
  </ItemGroup>

</Project>
